// Pays d'Asie et leurs principales villes et destinations.
// L'appli les affiche en ordre alphabétique. Pour en ajouter, il suffit de compléter les listes.
// On peut aussi ajouter une ville directement dans l'appli avec « Autre ville ».

export const VILLES = {
  'Afghanistan': ['Bamiyan', 'Hérat', 'Kaboul', 'Mazar-e Charif'],
  'Arabie saoudite': ['AlUla', 'Djeddah', 'Médine', 'Riyad'],
  'Arménie': ['Dilijan', 'Erevan', 'Gyumri', 'Sevan'],
  'Azerbaïdjan': ['Bakou', 'Gabala', 'Gandja', 'Sheki'],
  'Bahreïn': ['Manama', 'Muharraq'],
  'Bangladesh': ["Cox's Bazar", 'Chittagong', 'Dacca', 'Sreemangal', 'Sylhet'],
  'Bhoutan': ['Bumthang', 'Paro', 'Punakha', 'Thimphou'],
  'Brunei': ['Bandar Seri Begawan'],
  'Cambodge': ['Battambang', 'Kampot', 'Kep', 'Koh Rong', 'Koh Rong Samloem', 'Kratie', 'Phnom Penh', 'Siem Reap', 'Sihanoukville'],
  'Chine': ['Chengdu', 'Chongqing', 'Dali', 'Guangzhou', 'Guilin', 'Hangzhou', 'Lijiang', 'Pékin', 'Shanghai', 'Shenzhen', 'Suzhou', "Xi'an", 'Yangshuo', 'Zhangjiajie'],
  'Corée du Nord': ['Pyongyang'],
  'Corée du Sud': ['Andong', 'Busan', 'Daegu', 'Gangneung', 'Gyeongju', 'Incheon', 'Jeju', 'Jeonju', 'Séoul', 'Sokcho', 'Suwon', 'Yeosu'],
  'Émirats arabes unis': ['Abou Dabi', 'Dubaï', 'Ras el Khaïmah', 'Charjah'],
  'Géorgie': ['Batoumi', 'Kazbegi', 'Koutaïssi', 'Mestia', 'Sighnaghi', 'Tbilissi'],
  'Hong Kong': ['Hong Kong', 'Kowloon', 'Lantau', 'Lamma'],
  'Inde': ['Agra', 'Amritsar', 'Bangalore', 'Calcutta', 'Darjeeling', 'Delhi', 'Goa', 'Hampi', 'Jaipur', 'Jaisalmer', 'Jodhpur', 'Kochi', 'Leh', 'Manali', 'Mumbai', 'Munnar', 'Pondichéry', 'Pushkar', 'Rishikesh', 'Udaipur', 'Varanasi'],
  'Indonésie': ['Bandung', 'Canggu', 'Flores', 'Gili Air', 'Gili Trawangan', 'Jakarta', 'Komodo', 'Labuan Bajo', 'Lombok', 'Nusa Lembongan', 'Nusa Penida', 'Raja Ampat', 'Seminyak', 'Sumatra', 'Ubud', 'Uluwatu', 'Yogyakarta'],
  'Irak': ['Bagdad', 'Erbil', 'Souleimaniye'],
  'Iran': ['Chiraz', 'Ispahan', 'Kachan', 'Téhéran', 'Yazd'],
  'Israël': ['Eilat', 'Haïfa', 'Jérusalem', 'Tel Aviv'],
  'Japon': ['Fukuoka', 'Hakone', 'Hiroshima', 'Kanazawa', 'Kobe', 'Kyoto', 'Miyajima', 'Nagano', 'Nagasaki', 'Nara', 'Naoshima', 'Nikko', 'Niseko', 'Okinawa', 'Osaka', 'Sapporo', 'Takayama', 'Tokyo', 'Yokohama'],
  'Jordanie': ['Aqaba', 'Amman', 'Jerash', 'Pétra', 'Wadi Rum'],
  'Kazakhstan': ['Almaty', 'Astana', 'Chymkent', 'Turkestan'],
  'Kirghizistan': ['Bichkek', 'Karakol', 'Och', 'Song-Köl'],
  'Koweït': ['Koweït'],
  'Laos': ['Luang Namtha', 'Luang Prabang', 'Nong Khiaw', 'Paksé', 'Si Phan Don (4000 îles)', 'Thakhek', 'Vang Vieng', 'Vientiane'],
  'Liban': ['Baalbek', 'Beyrouth', 'Byblos', 'Tripoli'],
  'Macao': ['Macao', 'Taipa'],
  'Malaisie': ['Cameron Highlands', 'Ipoh', 'Kota Kinabalu', 'Kuala Lumpur', 'Kuching', 'Langkawi', 'Malacca', 'Penang (George Town)', 'Perhentian', 'Tioman'],
  'Maldives': ['Maafushi', 'Malé', 'Atoll d’Ari', 'Atoll de Baa'],
  'Mongolie': ['Désert de Gobi', 'Kharkhorin', 'Lac Khövsgöl', 'Oulan-Bator'],
  'Myanmar': ['Bagan', 'Hpa-An', 'Lac Inle', 'Mandalay', 'Ngapali', 'Yangon'],
  'Népal': ['Bhaktapur', 'Chitwan', 'Katmandou', 'Lukla', 'Pokhara'],
  'Oman': ['Mascate', 'Nizwa', 'Salalah', 'Sour'],
  'Ouzbékistan': ['Boukhara', 'Khiva', 'Samarcande', 'Tachkent'],
  'Pakistan': ['Hunza', 'Islamabad', 'Karachi', 'Lahore', 'Skardu'],
  'Philippines': ['Boracay', 'Bohol', 'Cebu', 'Coron', 'Davao', 'El Nido', 'Manille', 'Moalboal', 'Port Barton', 'Puerto Princesa', 'Siargao', 'Siquijor'],
  'Qatar': ['Doha'],
  'Singapour': ['Singapour'],
  'Sri Lanka': ['Arugam Bay', 'Colombo', 'Ella', 'Galle', 'Kandy', 'Mirissa', 'Nuwara Eliya', 'Sigiriya', 'Trincomalee', 'Unawatuna'],
  'Syrie': ['Alep', 'Damas', 'Palmyre'],
  'Tadjikistan': ['Douchanbé', 'Khorog', 'Pamir'],
  'Taïwan': ['Hualien', 'Jiufen', 'Kaohsiung', 'Kenting', 'Lac du Soleil et de la Lune', 'Tainan', 'Taichung', 'Taipei'],
  'Thaïlande': ['Ayutthaya', 'Bangkok', 'Chiang Mai', 'Chiang Rai', 'Hua Hin', 'Kanchanaburi', 'Khao Lak', 'Khao Sok', 'Koh Lanta', 'Koh Lipe', 'Koh Phangan', 'Koh Phi Phi', 'Koh Samui', 'Koh Tao', 'Krabi', 'Pai', 'Pattaya', 'Phuket', 'Railay', 'Sukhothai'],
  'Timor oriental': ['Atauro', 'Dili'],
  'Turkménistan': ['Achgabat', 'Darvaza', 'Merv'],
  'Turquie': ['Antalya', 'Bodrum', 'Cappadoce', 'Fethiye', 'Istanbul', 'Izmir', 'Kas', 'Pamukkale'],
  'Vietnam': ['Cat Ba', 'Da Lat', 'Da Nang', 'Ha Giang', 'Hanoï', 'Hô Chi Minh-Ville', 'Hoi An', 'Hué', 'Mui Ne', 'Nha Trang', 'Ninh Binh', 'Phong Nha', 'Phu Quoc', 'Baie d’Along', 'Sapa'],
  'Yémen': ['Aden', 'Sanaa', 'Socotra'],
};

const fr = (a, b) => a.localeCompare(b, 'fr', { sensitivity: 'base' });
export const trierFr = (liste) => [...liste].sort(fr);
export const PAYS_ASIE = trierFr(Object.keys(VILLES));
